---
title: "Untitled"
author: "Yen-Fong Li"
date: "2022-12-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("multiInput")
```


```{r cars}
# install.packages("usmap")
library(maps)
library(mapproj)
library(shiny)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(usmap)
library(plotly)
library(corrplot)

library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggpubr)
library(ggrepel)
library(GGally)
library(plotly)

install.packages("rcorr")
```

```{r}
covid_19_countdeath <- readRDS("www/data/count_death_cleaned_model.RDS")

#Select required columns   
covid_19_countdeath <- covid_19_countdeath[, c("cause_all", "cause_natural", "cause_other" ,"Septicemia (A40-A41)",
                                               "Malignant neoplasms (C00-C97)","Diabetes mellitus (E10-E14)", 
                                               "Alzheimer disease (G30)", 
                                               "Influenza and pneumonia (J09-J18)", 
                                               "Chronic lower respiratory diseases (J40-J47)" , 
                                               "Other diseases of respiratory system (J00-J06,J30-J39,J67,J70-J98)", 
                                               "Nephritis, nephrotic syndrome and nephrosis (N00-N07,N17-N19,N25-N27)", 
                                               "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified (R00-R99)", 
                                               "Diseases of heart (I00-I09,I11,I13,I20-I51)", 
                                               "Cerebrovascular diseases (I60-I69)", 
                                               "COVID-19 (U071, Underlying Cause of Death)")]


#Correlation analytics and significance level 
rcorr(covid_19_countdeath, type = c("pearson","spearman"))


res2 <- rcorr(as.matrix(covid_19_countdeath))
res2
```


#Dataset 1

## Import Data
```{r}
count_death_cleaned_model <- readRDS("www/data/count_death_cleaned_model.RDS")
count_death_cleaned_visual_1 <- readRDS("www/data/count_death_cleaned_visual_1.RDS")
count_death_cleaned_visual_2 <- readRDS("www/data/count_death_cleaned_visual_2.RDS")

count_death_cleaned_model
count_death_cleaned_visual_1
count_death_cleaned_visual_2
```

## Correlation Map
```{r}
diseases <- colnames(count_death_cleaned_model)[c(8,9,12:23)]
diseases
rename_diseases <- c("All Causes", "Natural Causes", "Septicemia", "Maligant neoplasms", "Diabetes mellitus", "Alzheimer disease",
  "Influenza and pneumonia", "Chronic lower respiratory", "Respiratory system", "Nephritis", "Symtoms signs", "Diseases of heart",
  "Cerebrovascular", "COVID-19")
count_death_cleaned_model
temp <- count_death_cleaned_model
temp$race %>% unique()
temp <- temp %>% filter(sex == "male")
temp
temp$year_death %>% unique
cor_count_death <- temp[,diseases]
cor_count_death
colnames(cor_count_death) <- rename_diseases
cor_count_death

# install.packages("corrplot")


correlation <- cor(cor_count_death)
corrplot(correlation)
# corrplot(correlation, method="circle", type='upper', tl.cex=0.7, tl.col = 'black')
```


## Bar Chart
```{r}
# Plot 1
# count_death_bar_1 <- count_death_bar
# count_death_bar$percents <- count_death_bar$death_by_disease / count_death_bar$cause_all

# count_death_bar <- count_death_bar %>% group_by(disease_type) %>% summarise(
#   total_counts = sum(death_by_disease), all_causes = cause_all)
# count_death_bar$all_causes <- sum(count_death_bar$all_causes)
# count_death_bar <- count_death_bar %>% unique()
# count_death_bar$percents <- count_death_bar$total_counts / count_death_bar$all_causes * 100


# Plot 2
count_death_cleaned_visual_2
count_death_bar <- count_death_cleaned_visual_2
count_death_bar <- filter(count_death_bar, sex %in% sexes)
count_death_bar_2 <- count_death_bar

# ggplot() +
#   geom_col(data = count_death_bar, aes(y = disease_type,x = death_by_disease, fill = age_group), position = "fill")



count_death_bar <- count_death_bar %>% group_by(disease_type) %>% summarise(
  total_counts = sum(death_by_disease))
count_death_bar

count_death_bar$sum_of_diseases <- sum(count_death_bar$total_counts)
count_death_bar
count_death_bar$percents_100 <- round(count_death_bar$total_counts / count_death_bar$sum_of_diseases * 100, 1)
count_death_bar <- count_death_bar %>% arrange(desc(percents_100))
count_death_bar


count_death_bar <- count_death_bar %>%  arrange(percents_100) %>% mutate(disease_type = factor(disease_type, levels = disease_type))
count_death_bar
disease_order <- count_death_bar$disease_type
disease_order

ggplot(count_death_bar, aes(y = disease_type, x = percents_100)) +
  geom_col() +
  geom_text(aes(label = paste(percents_100, "%"))) +
  scale_x_reverse() +
  scale_y_discrete(position = "right")

count_death_bar_2$disease_type <- ordered(count_death_bar_2$disease_type, disease_order)
count_death_bar_2
ggplot() +
  geom_col(data = count_death_bar_2, aes(y = disease_type,x = death_by_disease, fill = age_group), position = "fill")
```

## Loli
```{r}
loli <- count_death_cleaned_visual_2

loli <- subset(loli, select = c("date_start", "disease_type", "sex", "age_group", "death_by_disease"))
colnames(loli) <- c("date", "diseases", "sex", "age_group", "deaths")
loli %>% arrange(desc(date))
# filter date sex race
loli_plot1 <- loli
loli_plot1 <- loli_plot1 %>% group_by(diseases) %>% summarise(total_deaths <- sum(deaths))
colnames(loli_plot1)[2] <- "deaths"


loli_plot1$total_deaths <- sum(loli_plot1$deaths)
loli_plot1
loli_plot1$percent_100 <- round(loli_plot1$deaths / loli_plot1$total_deaths * 100, 1)
loli_plot1 <- loli_plot1 %>% arrange(desc(-percent_100))
new_order <- loli_plot1$diseases

ggplot(loli_plot1, aes(x = percent_100, y = reorder(diseases, percent_100))) +
  geom_text(aes(label = paste(percent_100, "%"), size = percent_100/6), vjust = -0.6, hjust = -0.3) +
  geom_point(aes(size = percent_100, color = percent_100), alpha = 0.5) +
  geom_segment(aes(
    x = 0,
    xend = percent_100,
    y = diseases,
    yend = diseases,
    color = percent_100
  )) +
  scale_size_continuous(range = c(5, 20)) +
  scale_x_reverse() +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.text.y = element_text(size = 30)) +
  scale_y_discrete(position = "right")
  

loli$diseases <- ordered(loli$diseases, levels = new_order)

ggplot(loli) +
  geom_col(aes(x = deaths, y = diseases, fill = age_group), position = "fill") +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()
  )

```



```{r}
sizes <- factor(c("Pencil", "brush", "pen"))
sizes
new <- c("Pencil", "brush", "pen")

sizes <- ordered(sizes, levels = new)
sizes
#> [1] small  large  large  small  medium
#> Levels: large medium small
```


# Dataset 2 
## Import Dataset
```{r}
condition_covi_cleaned <- readRDS("www/data/condition_covi_cleaned.RDS")
condition_covi_cleaned$state %>% unique()
```

# Map 
```{r}
remove_state <- c("United States", "Alaska", "American Samoa", "Hawaii", "New York City", "Puerto Rico")
temp <- condition_covi_cleaned %>% filter(group == "By Total" & !state %in% remove_state)
temp <- temp %>% filter(condition_group == "Respiratory diseases" & age_group == "All Ages")
temp
temp <- temp %>% group_by(state) %>% summarise(deathes = sum(covi_death)) 

# District of Columbia, 
temp
temp$deathes
temp$rank <- rank(-temp$deathes, ties.method = c("first"))
temp$state

shades <- colorRampPalette(c("darkgreen", "white"))(53)
shades
fills <- shades[temp$rank]
fills

maps::map("state", fill = TRUE, col = fills)
```
# Map 2
```{r}
map_2 <- condition_covi_cleaned
map_2
map_2 <- map_2 %>% filter(group == "By Month")
map_2 <- map_2 %>% mutate("date" = make_date(year = year, month = month))
map_2$covi_death[is.na(map_2$covi_death)] <- 0
map_2 <- map_2 %>% group_by(state) %>% summarise(deaths = sum(covi_death))
map_2

plot_usmap(data = map_2, values = "deaths", color = "red")

covi_data_cleaned_visual
map <- covi_data_cleaned_visual
map
# map <- map %>% filter(tolower(state) %in% states)
map <- map %>% filter(number_type == "tot_cases")
# map %>% filter(date > as.Date("2020-01-22"), date < as.Date("2020-01-27"))

map <- map %>% group_by(state) %>% summarise(total_cases = sum(number_value))
map


?scale_fill_continuous
plot_usmap(data = map, values = "total_cases", color = "red")

as.Date("2020-10-01") == as.Date("2020-10")
```



## Bar Chart
```{r}

## Plot 1
bar_chart_2 <- condition_covi_cleaned
bar_chart_2 <- bar_chart_2 %>% filter(age_group == "All Ages" & group == "By Total" & state != "United States")
bar_chart_2 <- bar_chart_2 %>% filter(state == "Alabama")
bar_chart_2$covi_death[is.na(bar_chart_2$covi_death)] <- 0
bar_chart_2$total_deaths <- sum(bar_chart_2$covi_death)
bar_chart_2 <- bar_chart_2 %>% group_by(condition_group, total_deaths) %>% summarise(deaths = sum(covi_death))
bar_chart_2$percents_100 <- bar_chart_2$deaths / bar_chart_2$total_deaths * 100


ggplot(bar_chart_2) +
  geom_col(aes(x = percents_100, y = condition_group)) +
  scale_y_discrete(position = "right") +
  scale_x_reverse()

## Plot 2
condition_covi_cleaned
bar_chart <- condition_covi_cleaned

bar_chart <- bar_chart %>% filter(state == "Alabama" & group == "By Total" & !age_group %in% c("Not stated", "All Ages"))

bar_chart$covi_death[is.na(bar_chart$covi_death)] <- 0
bar_chart


ggplot(bar_chart) +
  geom_col(aes(x = covi_death, y = condition_group, fill = age_group), position = "fill")
```
## Lolipop Chart
```{r}
loli <- condition_covi_cleaned
loli
loli <- loli %>% filter(group == "By Month" & state != "United State")
loli$covi_death[is.na(loli$covi_death)] <- 0
loli <- loli %>% mutate("date" = make_date(year = year, month = month))
loli <- loli %>% filter(state == "California")
loli <- subset(loli, select = c("date", "condition_group", "age_group", "covi_death"))
## Here loli filter by date
age_choices <- c("0-24")
loli <- loli %>% filter(age_group %in% age_choices)

loli_plot1 <- loli %>% group_by(condition_group) %>% summarise(total_deaths <- sum(covi_death))

loli <- loli %>% group_by(condition_group, age_group) %>% summarise(total_deaths <- sum(covi_death))


colnames(loli)[3] = "deaths"
colnames(loli_plot1)[2] = "deaths"


loli_plot1$total_deaths <- sum(loli_plot1$deaths)
loli_plot1$percent_100 <- round(loli_plot1$deaths / loli_plot1$total_deaths * 100, 1)
loli_plot1 <- loli_plot1 %>% arrange(desc(-percent_100))
new_order <- loli_plot1$condition_group

ggplot(loli_plot1, aes(x = percent_100, y = reorder(condition_group, percent_100))) +
  geom_text(aes(label = paste(percent_100, "%"), size = percent_100/6), vjust = -0.6, hjust = -0.3) +
  geom_point(aes(size = percent_100, color = percent_100), alpha = 0.5) +
  geom_segment(aes(
    x = 0,
    xend = percent_100,
    y = condition_group,
    yend = condition_group,
    color = percent_100
  )) +
  scale_size_continuous(range = c(5, 20)) +
  scale_x_reverse() +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.text.y = element_text(size = 10)) +
  scale_y_discrete(position = "right")

  


# loli <- loli %>% filter(!age_group %in% c("Not stated", "All Ages"))
loli$condition_group <- ordered(loli$condition_group, levels = new_order)

ggplot(loli) +
  geom_col(aes(x = deaths, y = condition_group, fill = age_group), position = "fill") +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()
  )

```





## Time Series
```{r}
condition_covi_cleaned
time_series <- condition_covi_cleaned
time_series <- time_series[,-11] %>% filter(group == "By Month")
# time_series <- time_series[,-11]
# time_series <- time_series %>% filter(group == "By Month")
time_series <- time_series %>% mutate("date" = make_date(year = year, month = month))
time_series <- time_series %>% filter(state == "Alabama" & age_group == "35-44")
time_series

# time_series$covi_death[is.na(time_series$covi_death)] <- 0
time_series <- time_series %>% drop_na()
# time_series %>% group_by(date, condition) %>% mutate(deaths = sum(covi_death))
time_series <- time_series %>% group_by(date, condition_group) %>% summarise(deaths = sum(covi_death))

time_series



p <- ggplot(time_series) +
  geom_line(aes(x = date, y = deaths, color = condition_group), size = 2)

ggplotly(p)

```

# Dataset 3
## Import Dataset
```{r}
covi_data_cleaned_model <- readRDS("www/data/covi_data_cleaned_model.RDS")
covi_data_cleaned_visual <- readRDS("www/data/covi_data_cleaned_visual.RDS")
covi_data_cleaned_model
covi_data_cleaned_visual
```
## Clear Data
clean unused states
```{r}
states <- c("alabama", "arizona", "arkansas", "california", "colorado", "connecticut", "delaware", "district of columbia", 
            "florida", "georgia", "idaho", "illinois", "indiana", "iowa", "kansas", "kentucky", "louisiana", "maine",
            "maryland", "massachusetts", "michigan", "minnesota", "mississippi", "missouri", "montana", "nebraska",
            "nevada", "new hampshire", "new jersey", "new mexico", "new york", "north carolina", "north dakota", "ohio",
            "oklahoma", "oregon", "pennsylvania", "rhode island", "south carolina", "south dakota", "washington",
            "west virginia", "wisconsin", "wyoming")
temp <- covi_data_cleaned_model %>% filter(tolower(covi_data_cleaned_model$state) %in% states)
temp$state %>% unique()
temp <- temp %>% group_by(date, state) %>% summarise(total_cases <- sum(tot_cases),
                                      new_case <- sum(new_case))
colnames(temp) <- c("date", "state", "total_cases", "new_cases")
temp
```



## Map
```{r}
covi_data_cleaned_visual
map <- covi_data_cleaned_visual
map
# map <- map %>% filter(tolower(state) %in% states)
map <- map %>% filter(number_type == "tot_cases")
# map %>% filter(date > as.Date("2020-01-22"), date < as.Date("2020-01-27"))

map <- map %>% group_by(state) %>% summarise(total_cases = sum(number_value))
map

library(usmap)

plot_usmap(data = map, values = "total_cases", color = "red")

```

## Time Series
```{r}

temp <- covi_data_cleaned_model
temp <- temp %>% filter(!state %in% c("United States", "New York City", "Puerto Rico"))
temp <- temp %>% filter(state == "California")
temp

ggplot(temp, aes(x = date)) +
  geom_area(aes(y = tot_cases), color = "blue", fill = "blue", size = 1) +
  geom_area(aes(y = new_case), color = "red", fill = "red", size = 1) 

```
### Heat Map
```{r}
heat <- covi_data_cleaned_model
## filter State
heat <- heat %>% group_by(day, month, year) %>% summarise(new_cases = sum(new_case))
heat <- subset(heat, select = c("day", "month", "year", "new_cases"))
heat <- heat %>% arrange(year, month, day)

?geom_tile
ggplot(heat, aes(month, day, fill = new_cases)) +
  geom_tile(width = 0.95) +
  facet_grid(year ~.)


ggplot(heat, aes(month, day, fill = new_cases)) +
  geom_tile(color = "white", size = 0.1, width = 0.95) +
  theme_minimal(base_size = 10) +
  scale_y_continuous(trans = "reverse", breaks = unique(df$day)) +
  scale_x_continuous(breaks =c(1:12)) +
  scale_fill_viridis(name="Hrly Temps C",option ="C") +
  # scale_fill_gradient(high = "red", low = "blue") +
  facet_grid(year ~.)
```

## Heat map reference
```{r}
# library(devtools)
# install_url('https://cran.r-project.org/src/contrib/Archive/Interpol.T/Interpol.T_2.1.1.tar.gz')
# install.packages("ggExtra")
library(ggplot2)
library(dplyr) # easier data wrangling 
library(viridis) # colour blind friendly palette, works in B&W also
library(Interpol.T) #  will generate a large dataset on initial load
library(lubridate) # for easy date manipulation
library(ggExtra) # because remembering ggplot theme options is beyond me
library(tidyr) 
 
 
data <- data(Trentino_hourly_T,package = "Interpol.T")
 
names(h_d_t)[1:5]<- c("stationid","date","hour","temp","flag")
df <- tbl_df(h_d_t) %>%
  filter(stationid =="T0001")
 
df <- df %>% mutate(year = year(date),
                  month = month(date, label=TRUE),
                  day = day(date))
df
  
df$date<-ymd(df$date) # not necessary for plot but 
#useful if you want to do further work with the data
 
#cleanup
rm(list=c("h_d_t","mo_bias","Tn","Tx",
          "Th_int_list","calibration_l",
          "calibration_shape","Tm_list"))
 
 
#create plotting df
df <-df %>% select(stationid,day,hour,month,year,temp)%>%
        fill(temp) #optional - see note below
 
# Re: use of fill
# This code is for demonstrating a visualisation technique
# There are 5 missing hourly values in the dataframe.
 
# see the original plot here (from my ggplot demo earlier this year) to see the white spaces where the missing values occcur:
# https://github.com/johnmackintosh/ggplotdemo/blob/master/temp8.png 
 
# I used 'fill' from  tidyr to take the prior value for each missing value and replace the NA
# This is a quick fix for the blog post only - _do not_ do this with your real world data
 
# Should really use either use replace_NA or complete(with fill)in tidyr 
# OR 
# Look into more specialist way of replacing these missing values -e.g. imputation.
 
 
 
statno <-unique(df$stationid)
df


 
 
######## Plotting starts here#####################
p <-ggplot(df,aes(day,hour,fill=temp))+
  geom_tile(color= "white",size=0.1) + 
  scale_fill_viridis(name="Hrly Temps C",option ="C")
p <-p + facet_grid(year~month)
p <-p + scale_y_continuous(trans = "reverse", breaks = unique(df$hour))
p <-p + scale_x_continuous(breaks =c(1,10,20,31))
p <-p + theme_minimal(base_size = 8)
p <-p + labs(title= paste("Hourly Temps - Station",statno), x="Day", y="Hour Commencing")
p <-p + theme(legend.position = "bottom")+
  theme(plot.title=element_text(size = 14))+
  theme(axis.text.y=element_text(size=6)) +
  theme(strip.background = element_rect(colour="white"))+
  theme(plot.title=element_text(hjust=0))+
  theme(axis.ticks=element_blank())+
  theme(axis.text=element_text(size=7))+
  theme(legend.title=element_text(size=8))+
  theme(legend.text=element_text(size=6))+
  removeGrid()#ggExtra
 
# you will want to expand your plot screen before this bit!
p #awesomeness
```



